version: '3.7'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - default
    volumes:
      - ".:/app"
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - web
  bot:
    build: ./ArthurBot
    ports:
      - "4000:4000"
    depends_on:
      - web
    networks:
      - default

networks:
  default: